author = "Ingmar && Jonathan"
subtitle = "Jonathan und Ingmar sprechen übers Programmieren und Ausliefern von Software Projekten. Außerdem tauschen die beiden Bremer sich über Tools, Framewoks und das Leben als Softwareentwickler aus."
avatar = "/cover-no-text.jpg"
since = "2019"
#home_mode = "post"
dateFormatToUse = "02.01.2006"
cdnURL = "https://cdn.codeandship.rocks"

[Social]
Github = "codeandship"
Twitter = "codeandship"
Spotify = "show/68VGe4DFCUxvcJp44VDVL3?si=AUTTI_xRST-wmsENs2ysCg"

