baseURL = "https://codeandship.rocks"
languageCode = "de"
defaultContentLanguage = "de"
title = "Code and Ship"
theme = "CodeAndShip"
publishDir = "public"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true